In [1]:
!pip install pandas    ##to install pandas

     |████████████████████████████████| 11.3 MB 8.1 MB/s eta 0:00:01    |██████▊                         | 2.4 MB 1.1 MB/s eta 0:00:09
     |████████████████████████████████| 15.7 MB 7.8 MB/s eta 0:00:01
     |████████████████████████████████| 503 kB 6.3 MB/s eta 0:00:01
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
matplotlib 3.4.3 requires cycler>=0.10, which is not installed.
matplotlib 3.4.3 requires kiwisolver>=1.0.1, which is not installed.
matplotlib 3.4.3 requires pillow>=6.2.0, which is not installed.
daal4py 2021.3.0 requires daal==2021.2.3, which is not installed.
conda-repo-cli 1.0.4 requires clyent>=1.2.0, which is not installed.
conda-repo-cli 1.0.4 requires pathlib, which is not installed.
conda-repo-cli 1.0.4 requires PyYAML>=3.12, which is not installed.
conda-build 3.21.6 requires beautifulsoup4, which is not installed.
conda-build 3.21.6 re

In [2]:
!pip install numpy     ##to install numpy


In [52]:
import numpy as np


In [19]:
a=np.array([1,2,3,4])
a.size

4

In [6]:
print(np.__version__)   ##print numpy version


1.21.4


In [6]:
print(a)

[1 2 3 4]


In [20]:
b=np.array([(1,2),(3,4)])

In [8]:
print(b)

[[1 2]
 [3 4]]


In [21]:
c=np.array([[1,2,3],[4,5,6]])  ##matrix
print(c)

[[1 2 3]
 [4 5 6]]


In [22]:
print((type(x)))

<class 'numpy.ndarray'>


In [11]:
print((type(a)))

<class 'numpy.ndarray'>


In [8]:
print(a.dtype)

int64


In [14]:
print(a.shape)

(4,)


In [23]:
print(b.shape)
print(x.shape)
print(c.shape)

(2, 2)
(2, 3)
(2, 3)


In [16]:
c=([(1,1),(1,1)])


In [17]:
sum=b+c
print(sum)

[[2 3]
 [4 5]]


In [18]:
prod=np.dot(b,c) ##matrix multiplication

In [19]:
print(prod)


[[3 3]
 [7 7]]


In [21]:
print(sum.sum())  ##sumof elements in an array

14


In [22]:
print(sum.sum(axis=0))

[6 8]


In [23]:
print(sum.sum(axis=1))

[5 9]


In [28]:
x=np.arange(10)

In [29]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [26]:
print(x[5])

5


In [30]:
x.resize(5,2)

In [28]:
print(x)


[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [31]:
print(x[:1])

[[0 1]]


In [32]:
print(x[:1,:1])

[[0]]


In [36]:
print(x[1:3,:2])

[[2 3]
 [4 5]]


In [33]:
n=np.random.random([3,3]) ##random elements

In [35]:
print (n)


[[0.13040098 0.46368684 0.32034773]
 [0.76176054 0.45910158 0.97384896]
 [0.93382953 0.82938595 0.01675412]]


In [38]:
a=np.arange(1,10)

In [39]:
print(a)
a.reshape(3,3) ##reshaping it as 2D array

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
b=np.arange(12,38)

In [41]:
print(b)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


In [43]:
print(b[::-1]) ##array reverse

[37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14
 13 12]


In [44]:
h = np.random.random((3,4)) #creating a numpy array having dimension (3,4) with random elements
print(h)

[[0.19728125 0.95276748 0.68086747 0.9867577 ]
 [0.63674429 0.81929717 0.33442519 0.58580733]
 [0.94007612 0.13922912 0.44884314 0.05589198]]


In [45]:
print(h.reshape(2,2,3)) ##reshaping it as two,2*3 arrays

[[[0.19728125 0.95276748 0.68086747]
  [0.9867577  0.63674429 0.81929717]]

 [[0.33442519 0.58580733 0.94007612]
  [0.13922912 0.44884314 0.05589198]]]


In [40]:
z = np.array([[1+0.j,2+5.j]]) ## numpy  array with complex numbers
print(z)
print(z.real)    ##printing real and imaginary parts
print(z.imag)

[[1.+0.j 2.+5.j]]
[[1. 2.]]
[[0. 5.]]


In [5]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [7]:
g=(1,2,3,4)  
g=np.array(g)   ##list to array

In [9]:
print(g)

[1 2 3 4]


In [10]:
a=np.arange(1,10)   ##3*3 matrix
print(a)
print(a.reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
b=np.zeros((3,3))  ##3*3 matrix with all zeroes
print(b)
b[2,2]=6        ##updating last element 
print(b)
b[-1,-1]=10
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 6.]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0. 10.]]


In [21]:
c=np.arange(2,11)
print(c)

[ 2  3  4  5  6  7  8  9 10]


In [22]:
f=np.asfarray(c) ##make array as float
print(f)

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [41]:
import numpy as np   ##convert numpy array to textfile
a = np.arange(1, 10)
np.savetxt('file.txt', a, delimiter=',')



In [14]:
import numpy as np       ##Interchange the axes or finding transpose
x = np.array([[1,2,3],[4,5,6]])
print(x)
y =  np.swapaxes(x,0,1)
print(y)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [53]:
import numpy as np      ##convert numpy array into csv file
data = np.array( [[10,20,30], [40,50,60], [70,80,90]] )
print(data)
np.savetxt("test.csv", data, delimiter=",")

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [54]:
a=np.array([1,2,3])

In [58]:
!pip install matplotlib

